development:
  host: localhost
  database: m_sample_app_development

test:
  host: localhost
  database: m_sample_app_test

# For using MongoHQ, we only need this variable in our heroku environment
production:
  uri: <%= ENV['MONGOHQ_URL'] %>

# set these environment variables on your prod server
# production:
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
